version: '2'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.RPi
    networks:
      - back
      - front
    volumes:
      - .:/var/www/playgrounds
      - ./app/cache/sf2/logs:/tmp/sf2/logs:rw
    ports:
      - "8000:8000"
  nginx:
    image: nginx:1.11-alpine
    volumes_from:
      - php
    volumes:
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - front
  mysql:
    image: hypriot/rpi-mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /mnt/sda1/var/lib/mysql-data/styletime:/var/lib/mysql
      - .:/var/www/styletime
    ports:
      - "3306:3306"
    networks:
      - back
networks:
  front: ~
  back: ~
