imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: pl

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

fos_rest:
    view:
        formats:
          json: true
          xml: true
        templating_formats:
            html: false
        jsonp_handler: ~
    format_listener:
        rules:
            path: '^/'
            priorities: ['json', 'xml']
            fallback_format: json
            prefer_extension: false
    routing_loader:
        default_format: json
        include_format: false
    versioning:
        enabled: true
        guessing_order:
            - query
            - custom_header
            - media_type
    body_converter:
        enabled: true
    param_fetcher_listener: true

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    notifications:
                        type: yml
                        dir: "%kernel.root_dir%/../src/Playgrounds/Infrastructure/ORM/Mapping/"
                        prefix: Playgrounds\Domain
                        is_bundle: false

nelmio_cors:
    paths:
      '^/':
          allow_credentials: true
          allow_origin: ['*']
          allow_headers: ['Origin', 'X-Requested-With', 'Content-Type', 'Accept', 'Authorization']
          allow_methods: ['POST','GET','DELETE','PUT','PATCH']
          expose_headers: ['X-Page-Count', 'X-Count']

stof_doctrine_extensions:
    default_locale: "%locale%"
    translation_fallback: true
    orm:
        default:
            sluggable: true
            loggable: true
            timestampable: true
