Playgrounds\Domain\PlaygroundsLogs:
  type: entity
  table: playgroundsLogs
  readOnly: true
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    action:
      type: string
      length: 8
    loggedAt:
      type: datetime
      name: logged_at
    objectId:
      type: string
      name: object_id
      length: 64
      nullable: true
    objectClass:
      type: string
      name: object_class
      length: 255
    version:
      type: integer
    data:
      type: array
      nullable: true
    username:
      type: string
      length: 255
      nullable: true
